### ISSUE TITLE
Occupancy ground truth data generation - question

### ISSUE THREAD

**Issue by aprath1** [elchun/lndf_robot#1]
Could you please share how you are generating occupancy ground truths for the point cloud data generated with the 'shapenet_pcd_gen.py' ?
The file only generates point cloud using pybullet simulation and I was wondering for these point clouds, how you have generated the occupancy ground truths. Is it possible to integrate it in the same (shapenet_pcd_gen) pipeline?

Thanks

**Comment by elchun** [comment]
Hi @aprath1,
Thanks for the question.  Please see this issue from the Neural Descriptor Fields repo: https://github.com/anthonysimeonov/ndf_robot/issues/10.  This portion of the codebase is very similar to ours.  I believe you can voxelize the meshes and sample within the bounding box of the objects.  Then use importance sampling to balance the number of positive and negative samples.

**Comment by aprath1** [comment]
Ok, Thank you for your response, will try it out.
