### ISSUE TITLE
Asking for the library to generate the occupancy ground truth data

### ISSUE THREAD

**Issue by yijionglin** [elchun/lndf_robot#2]
Hi there,

Thanks for sharing such great work!!!

I also have a similar question to [the issue from ndf_robot](https://github.com/anthonysimeonov/ndf_robot/issues/10) and the [issue](https://github.com/elchun/lndf_robot/issues/1) here. To my knowledge, the way to get the voxel value described in[ the occupancy network paper](https://github.com/autonomousvision/occupancy_networks) is:

1. get the CAD models from ShapeNet,
2. make the models watertight for determining the occupancy value,
3. center and rescale them into a unit cube for sampling points,
4. sample pairs of random points and occupancy value.

Based on that, I'm confused: to my understanding, these steps are not used in your method, as you voxelize the meshes and use voxel to determine the occupancy value, which does not need to be watertight. Is it correct?

If this is correct, could I know which library you use to generate the voxel value? Open3D? I'm a newbie to the voxel stuff and not sure which one is the best to do it. 

All the best,

**Comment by yijionglin** [comment]
Interestingly I found [this piece of code](https://github.com/elchun/lndf_robot/blob/5418659b02839cee00d7a7703dfda8ba93b232f8/src/ndf_robot/utils/three_util.py#L58C7-L58C7) in three_util.py in the utils folder:

It looks like this is the code to generate the occupancy ground truth data, and I assume the `obj_mesh` should be imported with `trimesh.load_mesh` and the `mesh_to_voxels` function is from this [repo](https://github.com/marian42/mesh_to_sdf#mesh_to_voxels)? I'm gonna give it a go, but any suggestions for this bit would be appreciated!

All the best,

**Comment by aprath1** [comment]
Hi @yijionglin,
did you manage to get the ground truth data with the above approach?

**Comment by elchun** [comment]
Hi @yijionglin,
Apologies for the delay.  I believe you are correct in using trimesh and the mesh_to_voxels function.  In general, we use the same mesh loading infrastructure as [ndf_robot](https://github.com/anthonysimeonov/ndf_robot) so any pipeline that works with the ndf_robot repo should work for this one as well.

**Comment by yijionglin** [comment]
> Hi @yijionglin, Apologies for the delay. I believe you are correct in using trimesh and the mesh_to_voxels function. In general, we use the same mesh loading infrastructure as [ndf_robot](https://github.com/anthonysimeonov/ndf_robot) so any pipeline that works with the ndf_robot repo should work for this one as well.

Thanks for your kind reply! A quick question, is this LNDF built on top of the original NDF implementation? The code structure looks mainly the same but I'm not sure...

All the best,
Yijiong

**Comment by elchun** [comment]
Hi @yijionglin, that's correct -- the mesh loading and visualization are from the original NDF implementation while the model implementation and loss functions are specific to LNDF.

Best, 
Ethan
